move built to aws registry
Signed-off-by: Alexandre Ferreira <alexjorgef@protonmail.com>

diff --git a/env b/env
--- a/env
+++ b/env
@@ -66,6 +66,7 @@ function main() {
     fi
 
     set -euo pipefail
+
     eval set -- "$args"
 
     while true; do
@@ -139,6 +140,9 @@ function main() {
                 --disk-size ${MINIKUBE_HW_DISK_SIZE} \
                 --mount-string="$(pwd):/mnt/diadata:rw" \
                 --mount=true
+            eval "$(minikube -p ${MINIKUBE_PROFILE} docker-env)"
+            docker login --username=alex1a
+            eval "$(minikube -p ${MINIKUBE_PROFILE} docker-env --unset)"
         else
             echo "Unknown command" >&2
             exit 1
@@ -223,25 +227,37 @@ function main() {
             # echo "${@:1}"
             # echo "${@:2}"
             # sha256sum README.md | head -c 10
+            # TODO: this is only needed because minikube image build font return error exit code
+            #   see https://github.com/kubernetes/minikube/issues/16576
             if [[ "$MINIKUBE_DRIVER" == "docker" ]]; then
                 echo "Building minikube images ..."
                 eval "$(minikube -p ${MINIKUBE_PROFILE} docker-env)"
 
-                source ./baseimage.sh --notpush
+                # source ./baseimage.sh --notpush
 
-                docker buildx build -f "build/Dockerfile-filtersBlockService" -t "diadata.filtersblockservice:latest" .
-                docker buildx build -f "build/Dockerfile-tradesBlockService" -t "diadata.tradesblockservice:latest" .
-                docker buildx build -f "build/Dockerfile-pairDiscoveryService" -t "diadata.pairdiscoveryservice:latest" .
-                docker buildx build -f "build/Dockerfile-genericCollector" -t "diadata.genericcollector:latest" .
-                docker buildx build -f "build/Dockerfile-genericCollector-Dev" -t "diadata.genericcollector.dev:latest" .
-                docker buildx build -f "build/Dockerfile-blockchainservice" -t "diadata.blockchainservice:latest" .
-                docker buildx build -f "build/Dockerfile-assetCollectionService" -t "diadata.assetcollectionservice:latest" .
-                docker buildx build -f "build/Dockerfile-liquidityScraper" -t "diadata.liquidityscraper:latest" .
-                docker buildx build -f "build/Dockerfile-genericForeignScraper" -t "diadata.genericforeignscraper:latest" .
-                docker buildx build -f "build/Dockerfile-genericForeignScraper-Dev" -t "diadata.genericforeignscraper.dev:latest" .
+                # docker buildx build -f "build/Dockerfile-filtersBlockService" -t "diadata.filtersblockservice:latest" .
+                # docker buildx build -f "build/Dockerfile-tradesBlockService" -t "diadata.tradesblockservice:latest" .
+                # docker buildx build -f "build/Dockerfile-pairDiscoveryService" -t "diadata.pairdiscoveryservice:latest" .
+                # docker buildx build -f "build/Dockerfile-blockchainservice" -t "diadata.blockchainservice:latest" .
+                # docker buildx build -f "build/Dockerfile-assetCollectionService" -t "diadata.assetcollectionservice:latest" .
+                # docker buildx build -f "build/Dockerfile-liquidityScraper" -t "diadata.liquidityscraper:latest" .
+                # docker buildx build -f "build/Dockerfile-genericCollector" -t "diadata.genericcollector:latest" .
+                # docker buildx build -f "build/Dockerfile-genericForeignScraper" -t "diadata.genericforeignscraper:latest" .
+
+                docker buildx build -f "build/build/Dockerfile-DiadataBuild-114-Dev" -t "dia.build-114.dev:latest" .
+                docker buildx build -f "build/build/Dockerfile-DiadataBuild-117-Dev" -t "dia.build-117.dev:latest" .
+                docker buildx build -f "build/build/Dockerfile-DiadataBuild-119-Dev" -t "dia.build-119.dev:latest" .
+                docker buildx build -f "build/Dockerfile-filtersBlockService-Dev" -t "dia.filtersblockservice.dev:latest" .
+                docker buildx build -f "build/Dockerfile-tradesBlockService-Dev" -t "dia.tradesblockservice.dev:latest" .
+                docker buildx build -f "build/Dockerfile-pairDiscoveryService-Dev" -t "dia.pairdiscoveryservice.dev:latest" .
+                docker buildx build -f "build/Dockerfile-blockchainservice-Dev" -t "dia.blockchainservice.dev:latest" .
+                docker buildx build -f "build/Dockerfile-assetCollectionService-Dev" -t "dia.assetcollectionservice.dev:latest" .
+                docker buildx build -f "build/Dockerfile-liquidityScraper-Dev" -t "dia.liquidityscraper.dev:latest" .
+                docker buildx build -f "build/Dockerfile-genericCollector-Dev" -t "dia.genericcollector.dev:latest" .
+                docker buildx build -f "build/Dockerfile-genericForeignScraper-Dev" -t "dia.genericforeignscraper.dev:latest" .
 
                 eval "$(minikube -p ${MINIKUBE_PROFILE} docker-env --unset)"
-                echo "Build finished"
+                echo "All DIA's images build successfully"
             else
                 minikube -p ${MINIKUBE_PROFILE} image build -t us.icr.io/dia-registry/devops/build:latest -f build/build/Dockerfile-DiadataBuild .
                 minikube -p ${MINIKUBE_PROFILE} image build -t us.icr.io/dia-registry/devops/build-117:latest -f build/build/Dockerfile-DiadataBuild-117 .
@@ -536,6 +552,74 @@ function main() {
         fi
         ;;
     info)
+        echo "PWD: $PWD"
+        echo "SCRIPT_FOLDER: $SCRIPT_FOLDER"
+        if [[ "$OSTYPE" == "linux-gnu"* ]]; then
+            echo "OSTYPE: GNU/Linux"
+        elif [[ "$OSTYPE" == "darwin"* ]]; then
+            echo "OSTYPE: Mac OSX"
+        fi
+        uptime=$(minikube -p ${MINIKUBE_PROFILE} ssh -- uptime -p)
+        echo "Uptime: $uptime"
+        echo; echo "Images:"
+        minikube -p ${MINIKUBE_PROFILE} image ls
+
+        echo; echo "Status:"
+        minikube -p ${MINIKUBE_PROFILE} status
+        
+        echo; echo "Disk available:"
+        minikube -p ${MINIKUBE_PROFILE} ssh -- df -h
+        if [[ "$MINIKUBE_DRIVER" == "docker" ]]; then
+            echo; echo "Disk available of Docker:"
+            minikube -p ${MINIKUBE_PROFILE} ssh -- docker system df
+        fi
+        ;;
+    ping)
+        # minikube -p ${MINIKUBE_PROFILE} kubectl -- \
+        #     exec -it deployment/influx -- \
+        #     influx -host 'influx.default.svc.cluster.local' -port '8086' -execute 'SHOW DATABASES' >/dev/null 2>&1 && echo "InfluxDB OK" || echo "InfluxDB FAILED" >&2
+        echo; echo "Ping tests:"
+        minikube -p ${MINIKUBE_PROFILE} kubectl -- \
+            delete -f deployments/k8s-yaml/job-ping-redis.yaml >/dev/null 2>&1 || true
+        minikube -p ${MINIKUBE_PROFILE} kubectl -- \
+            create -f deployments/k8s-yaml/job-ping-redis.yaml >/dev/null 2>&1
+        minikube -p ${MINIKUBE_PROFILE} kubectl -- \
+            wait --timeout=30s --for=condition=complete job/ping-redis >/dev/null 2>&1 && echo "  Redis OK" || echo "  Redis FAILED" >&2
+        minikube -p ${MINIKUBE_PROFILE} kubectl -- \
+            delete -f deployments/k8s-yaml/job-ping-influx.yaml >/dev/null 2>&1 || true
+        minikube -p ${MINIKUBE_PROFILE} kubectl -- \
+            create -f deployments/k8s-yaml/job-ping-influx.yaml >/dev/null 2>&1
+        minikube -p ${MINIKUBE_PROFILE} kubectl -- \
+            wait --timeout=30s --for=condition=complete job/ping-influx >/dev/null 2>&1 && echo "  InfluxDB OK" || echo "  InfluxDB FAILED" >&2
+        minikube -p ${MINIKUBE_PROFILE} kubectl -- \
+            delete -f deployments/k8s-yaml/job-ping-postgres.yaml >/dev/null 2>&1 || true
+        minikube -p ${MINIKUBE_PROFILE} kubectl -- \
+            create -f deployments/k8s-yaml/job-ping-postgres.yaml >/dev/null 2>&1
+        minikube -p ${MINIKUBE_PROFILE} kubectl -- \
+            wait --timeout=30s --for=condition=complete job/ping-postgres >/dev/null 2>&1 && echo "  PostgreSQL OK" || echo "  PostgreSQL FAILED" >&2
+        minikube -p ${MINIKUBE_PROFILE} kubectl -- \
+            delete -f deployments/k8s-yaml/job-ping-kafka.yaml >/dev/null 2>&1 || true
+        minikube -p ${MINIKUBE_PROFILE} kubectl -- \
+            create -f deployments/k8s-yaml/job-ping-kafka.yaml >/dev/null 2>&1
+        minikube -p ${MINIKUBE_PROFILE} kubectl -- \
+            wait --timeout=30s --for=condition=complete job/ping-kafka >/dev/null 2>&1 && echo "  Kafka OK" || echo "  Kafka FAILED" >&2
+        # minikube -p ${MINIKUBE_PROFILE} kubectl -- \
+        #     exec -it deployment/postgres -- \
+        #     pg_isready -h 'postgres.default.svc.cluster.local' -U 'postgres' >/dev/null 2>&1 && echo "PostgreSQL OK" || echo "PostgreSQL FAILED" >&2
+        # minikube -p ${MINIKUBE_PROFILE} kubectl -- \
+        #     exec -it deployment/redis -- \
+        #     redis-cli -u 'redis://redis.default.svc.cluster.local:6379/0' ping >/dev/null 2>&1 && echo "Redis OK" || echo "Redis FAILED" >&2
+        # minikube -p ${MINIKUBE_PROFILE} kubectl -- \
+        #     run x --image=influxdb:1.8 --restart=Never --command -- \
+        #     influx -host 'influx.default.svc.cluster.local' -port '8086' -execute 'SHOW DATABASES'
+        # minikube -p ${MINIKUBE_PROFILE} kubectl -- \
+        #     exec -it deployment/redis -- \
+        #     echo dump | nc kafka.default.svc.cluster.local 9094 | grep brokers
+        # kafkacat -b "kafka.default.svc.cluster.local:9094" -L
+        # >/dev/null 2>&1 && echo "Redis OK" || echo "Redis FAILED" >&2
+        # https://stackoverflow.com/a/28353785/2042014
+        ;;
+    list)
         if [ "${#paths[@]}" -gt 1 ]; then
             case "${paths[1]}" in
             exchange)
@@ -643,72 +727,6 @@ function main() {
                 ;;
             esac
         else
-            echo "PWD: $PWD"
-            echo "SCRIPT_FOLDER: $SCRIPT_FOLDER"
-            if [[ "$OSTYPE" == "linux-gnu"* ]]; then
-                echo "OSTYPE: GNU/Linux"
-            elif [[ "$OSTYPE" == "darwin"* ]]; then
-                echo "OSTYPE: Mac OSX"
-            fi
-            uptime=$(minikube -p ${MINIKUBE_PROFILE} ssh -- uptime -p)
-            echo "Uptime: $uptime"
-            echo; echo "Images:"
-            minikube -p ${MINIKUBE_PROFILE} image ls
-
-            echo; echo "Status:"
-            minikube -p ${MINIKUBE_PROFILE} status
-            
-            echo; echo "Disk available:"
-            minikube -p ${MINIKUBE_PROFILE} ssh -- df -h
-            if [[ "$MINIKUBE_DRIVER" == "docker" ]]; then
-                echo; echo "Disk available of Docker:"
-                minikube -p ${MINIKUBE_PROFILE} ssh -- docker system df
-            fi
-
-             # minikube -p ${MINIKUBE_PROFILE} kubectl -- \
-            #     exec -it deployment/influx -- \
-            #     influx -host 'influx.default.svc.cluster.local' -port '8086' -execute 'SHOW DATABASES' >/dev/null 2>&1 && echo "InfluxDB OK" || echo "InfluxDB FAILED" >&2
-            echo; echo "Ping tests:"
-            minikube -p ${MINIKUBE_PROFILE} kubectl -- \
-                delete -f deployments/k8s-yaml/job-ping-redis.yaml >/dev/null 2>&1 || true
-            minikube -p ${MINIKUBE_PROFILE} kubectl -- \
-                create -f deployments/k8s-yaml/job-ping-redis.yaml >/dev/null 2>&1
-            minikube -p ${MINIKUBE_PROFILE} kubectl -- \
-                wait --timeout=30s --for=condition=complete job/ping-redis >/dev/null 2>&1 && echo "  Redis OK" || echo "  Redis FAILED" >&2
-            minikube -p ${MINIKUBE_PROFILE} kubectl -- \
-                delete -f deployments/k8s-yaml/job-ping-influx.yaml >/dev/null 2>&1 || true
-            minikube -p ${MINIKUBE_PROFILE} kubectl -- \
-                create -f deployments/k8s-yaml/job-ping-influx.yaml >/dev/null 2>&1
-            minikube -p ${MINIKUBE_PROFILE} kubectl -- \
-                wait --timeout=30s --for=condition=complete job/ping-influx >/dev/null 2>&1 && echo "  InfluxDB OK" || echo "  InfluxDB FAILED" >&2
-            minikube -p ${MINIKUBE_PROFILE} kubectl -- \
-                delete -f deployments/k8s-yaml/job-ping-postgres.yaml >/dev/null 2>&1 || true
-            minikube -p ${MINIKUBE_PROFILE} kubectl -- \
-                create -f deployments/k8s-yaml/job-ping-postgres.yaml >/dev/null 2>&1
-            minikube -p ${MINIKUBE_PROFILE} kubectl -- \
-                wait --timeout=30s --for=condition=complete job/ping-postgres >/dev/null 2>&1 && echo "  PostgreSQL OK" || echo "  PostgreSQL FAILED" >&2
-            minikube -p ${MINIKUBE_PROFILE} kubectl -- \
-                delete -f deployments/k8s-yaml/job-ping-kafka.yaml >/dev/null 2>&1 || true
-            minikube -p ${MINIKUBE_PROFILE} kubectl -- \
-                create -f deployments/k8s-yaml/job-ping-kafka.yaml >/dev/null 2>&1
-            minikube -p ${MINIKUBE_PROFILE} kubectl -- \
-                wait --timeout=30s --for=condition=complete job/ping-kafka >/dev/null 2>&1 && echo "  Kafka OK" || echo "  Kafka FAILED" >&2
-            # minikube -p ${MINIKUBE_PROFILE} kubectl -- \
-            #     exec -it deployment/postgres -- \
-            #     pg_isready -h 'postgres.default.svc.cluster.local' -U 'postgres' >/dev/null 2>&1 && echo "PostgreSQL OK" || echo "PostgreSQL FAILED" >&2
-            # minikube -p ${MINIKUBE_PROFILE} kubectl -- \
-            #     exec -it deployment/redis -- \
-            #     redis-cli -u 'redis://redis.default.svc.cluster.local:6379/0' ping >/dev/null 2>&1 && echo "Redis OK" || echo "Redis FAILED" >&2
-            # minikube -p ${MINIKUBE_PROFILE} kubectl -- \
-            #     run x --image=influxdb:1.8 --restart=Never --command -- \
-            #     influx -host 'influx.default.svc.cluster.local' -port '8086' -execute 'SHOW DATABASES'
-            # minikube -p ${MINIKUBE_PROFILE} kubectl -- \
-            #     exec -it deployment/redis -- \
-            #     echo dump | nc kafka.default.svc.cluster.local 9094 | grep brokers
-            # kafkacat -b "kafka.default.svc.cluster.local:9094" -L
-            # >/dev/null 2>&1 && echo "Redis OK" || echo "Redis FAILED" >&2
-            # https://stackoverflow.com/a/28353785/2042014
-            
             echo; echo "InfluxDB Data:"
             # TODO: SELECT * is slow
             num_tradestmp=$(minikube -p ${MINIKUBE_PROFILE} kubectl -- \
