add insert, delete sql queries
Signed-off-by: Alexandre Ferreira <alexjorgef@protonmail.com>

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -97,6 +97,9 @@ function main()
 
     MINIKUBE_PROFILE=dia
     MINIKUBE_K8S_VERSION=v1.25.7
+    MINIKUBE_HW_DISK_SIZE=50g
+    MINIKUBE_HW_CPUS=4
+    MINIKUBE_HW_RAM=8g
     MINIKUBE_DRIVER=docker
     MINIKUBE_CERT_MOUNT=~/.minikube
     # kubectl configuration to use
@@ -104,7 +107,12 @@ function main()
 
     case "${paths[0]}" in
         minikube-start)
-            minikube -p ${MINIKUBE_PROFILE} start --kubernetes-version ${MINIKUBE_K8S_VERSION} --driver ${MINIKUBE_DRIVER} 
+            minikube -p ${MINIKUBE_PROFILE} start \
+                --kubernetes-version ${MINIKUBE_K8S_VERSION} \
+                --driver ${MINIKUBE_DRIVER} \
+                --memory ${MINIKUBE_HW_RAM} \
+                --cpus ${MINIKUBE_HW_CPUS} \
+                --disk-size ${MINIKUBE_HW_DISK_SIZE}
             ;;
         minikube-stop)
             minikube -p ${MINIKUBE_PROFILE} stop
@@ -114,6 +122,9 @@ function main()
             ;;
         minikube-log)
             minikube -p ${MINIKUBE_PROFILE} logs -f
+            ;;
+        minikube-info)
+            minikube profile list
             ;;
         minikube-status)
             minikube -p ${MINIKUBE_PROFILE} status
@@ -125,6 +136,9 @@ function main()
             minikube delete -p ${MINIKUBE_PROFILE}
             # TODO: remove all minikube mount files
             # rm -rf ./.temp-tester/
+            docker image prune -a -f
+            docker volume prune -a -f
+            docker network prune -f
             ;;
         minikube-build)
             # echo "Building minikube images ..."
@@ -150,6 +164,8 @@ function main()
             minikube -p ${MINIKUBE_PROFILE} image build -t us.icr.io/dia-registry/devops/build-117:latest -f build/build/Dockerfile-DiadataBuild-117 .
             minikube -p ${MINIKUBE_PROFILE} image build -t diadata.filtersblockservice:latest -f build/Dockerfile-filtersBlockService .
             minikube -p ${MINIKUBE_PROFILE} image build -t diadata.tradesblockservice:latest -f build/Dockerfile-tradesBlockService .
+            minikube -p ${MINIKUBE_PROFILE} image build -t diadata.pairdiscoveryservice:latest -f build/Dockerfile-pairDiscoveryService .
+            minikube -p ${MINIKUBE_PROFILE} image build -t diadata.exchangescrapercollector:latest -f build/Dockerfile-genericCollector .
             ;;
         minikube-install)
             minikube -p ${MINIKUBE_PROFILE} kubectl -- create -f deployments/k8s-yaml/install.yaml
@@ -163,13 +179,124 @@ function main()
         minikube-uninstall)
             minikube -p ${MINIKUBE_PROFILE} kubectl -- delete -f deployments/k8s-yaml/install.yaml
             ;;
+        minikube-psqlinsert)
+            inputExchangeName="Custom"
+            # echo "Exchange Name:"
+            # read -r inputExchangeName
+            # while true; do
+            #     echo "The exchange is decentralized in a blockchain?"
+            #     read -r inputExchangeCentralized
+            #     case $inputExchangeCentralized in
+            #         [Yy]* ) echo "You choose yes."; break;;
+            #         [Nn]* ) echo "You choose no.";;
+            #         * ) echo "Please answer yes or no.";;
+            #     esac
+            # done
+            # echo "$inputExchangeCentralized"
+            # while true; do
+            #     echo "The exchange is a bridge?"
+            #     read -r inputExchangeBridge
+            #     case $inputExchangeBridge in
+            #         [Yy]* ) echo "You choose yes."; break;;
+            #         [Nn]* ) echo "You choose no.";;
+            #         * ) echo "Please answer yes or no.";;
+            #     esac
+            # done
+            # echo "$inputExchangeBridge"
+            minikube -p ${MINIKUBE_PROFILE} kubectl -- \
+                exec -it deployment/postgres -- \
+                psql -v ON_ERROR_STOP=on -U postgres \
+                -c "INSERT INTO exchange (
+                    exchange_id,
+                    name,
+                    centralized,
+                    bridge,
+                    contract,
+                    blockchain,
+                    rest_api,
+                    ws_api,
+                    pairs_api,
+                    watchdog_delay,
+                    scraper_active
+                ) VALUES(
+                    gen_random_uuid(),
+                    'Custom',
+                    true,
+                    false,
+                    '',
+                    '',
+                    '',
+                    'wss://ws-feed.pro.coinbase.com',
+                    'https://api.pro.coinbase.com/products',
+                    300,
+                    true
+                )
+                ;" >/dev/null 2>&1 && echo "Success" || echo "Error, a exchange with the name $inputExchangeName already exists." >&2
+            # set +e
+            # psqlExitCode=$?
+            # if [ $psqlExitCode -ne 0 ]; then
+            #     echo "Error, a exchange with the name $inputExchangeName already exists."
+            # else
+            #     echo "Success"
+            # fi
+            ;;
+        minikube-psqldelete)
+            # TODO: error handling when cannot delete row
+            minikube -p ${MINIKUBE_PROFILE} kubectl -- \
+                exec -it deployment/postgres -- \
+                psql -U postgres -t \
+                -c "DELETE FROM exchange WHERE name = 'Custom'" >/dev/null 2>&1 && echo "Row deleted." || echo "Error, a exchange does not exists and cannot be deleted." >&2
+            ;;
+        minikube-psqlfind)
+            # minikube -p ${MINIKUBE_PROFILE} kubectl -- \
+            #     exec -it deployment/postgres -- \
+            #     psql -U postgres -t \
+            #     -c "SELECT exchange_id FROM exchange WHERE name = 'Custom'" \
+            #     -c "SELECT exchange_id FROM exchange WHERE name = 'Custom'"
+            minikube -p ${MINIKUBE_PROFILE} kubectl -- \
+                exec -it deployment/postgres -- \
+                psql -U postgres -t \
+                -c "SELECT exchange_id FROM exchange WHERE name = 'Custom'" | if [[ $(wc -l) -ge 2 ]]; then echo "Found"; else echo "Not Found"; fi
+                # -c "SELECT exchange_id FROM exchange WHERE name = 'Custom';
+                #     IF NOT FOUND THEN RAISE EXCEPTION 'User not found'"
+                # "select coalesce(
+                #     (select name from exchange where name = 'CustomA'), '(none)'
+                # )"
+            # echo $?
+            ;;
         minikube-create)
-            minikube -p ${MINIKUBE_PROFILE} image build -t diadata.pairdiscoveryservice:latest -f build/Dockerfile-pairDiscoveryService .
-            minikube -p ${MINIKUBE_PROFILE} image build -t diadata.exchangescrapercollector:latest -f build/Dockerfile-genericCollector .
-            minikube -p ${MINIKUBE_PROFILE} kubectl -- create -f deployments/k8s-yaml/exchangescraper-custom.yaml
+            if [ "${#paths[@]}" -gt 1 ]; then
+                echo "${#paths[@]}"
+                case "${paths[1]}" in
+                    exchange)
+                        minikube -p ${MINIKUBE_PROFILE} kubectl -- create -f deployments/k8s-yaml/exchangescraper-custom.yaml
+                        ;;
+                    *)
+                        echo "Unknown command" >&2
+                        exit 1
+                        ;;
+                esac
+            else
+                echo "Unknown command" >&2
+                exit 1
+            fi
             ;;
         minikube-remove)
-            minikube -p ${MINIKUBE_PROFILE} kubectl -- delete -f deployments/k8s-yaml/exchangescraper-custom.yaml
+            if [ "${#paths[@]}" -gt 1 ]; then
+                echo "${#paths[@]}"
+                case "${paths[1]}" in
+                    exchange)
+                        minikube -p ${MINIKUBE_PROFILE} kubectl -- delete -f deployments/k8s-yaml/exchangescraper-custom.yaml
+                        ;;
+                    *)
+                        echo "Unknown command" >&2
+                        exit 1
+                        ;;
+                esac
+            else
+                echo "Unknown command" >&2
+                exit 1
+            fi
             ;;
         recreate)
             docker_service drop "${@:2}"
@@ -185,7 +312,7 @@ function main()
             docker compose -f ~/dotfiles/dist/deploy/compose.yaml build --pull --progress plain "${@:2}"
             ;;
         *)
-            echo "Unknown service command" >&2
+            echo "Unknown command" >&2
             exit 1
             ;;
     esac
